/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * SRI Monitoring API
 * HTTP JSON API for monitoring SV2 applications
 * OpenAPI spec version: 0.1.0
 */

export interface ErrorResponse {
  error: string;
}

/**
 * Information about an extended channel
 */
export interface ExtendedChannelInfo {
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  expected_shares_per_minute: number;
  extranonce_prefix_hex: string;
  /** @minimum 0 */
  full_extranonce_size: number;
  /** @minimum 0 */
  last_batch_accepted: number;
  last_batch_work_sum: number;
  /** @minimum 0 */
  last_share_sequence_number: number;
  nominal_hashrate: number;
  requested_max_target_hex: string;
  /** @minimum 0 */
  rollable_extranonce_size: number;
  /** @minimum 0 */
  share_batch_size: number;
  share_work_sum: number;
  /** @minimum 0 */
  shares_accepted: number;
  target_hex: string;
  user_identity: string;
}

/**
 * Aggregate information about the server connection
 */
export interface ServerSummary {
  /** @minimum 0 */
  extended_channels: number;
  /** @minimum 0 */
  standard_channels: number;
  /** @minimum 0 */
  total_channels: number;
  total_hashrate: number;
}

/**
 * Aggregate information about SV1 client connections
 */
export interface Sv1ClientsSummary {
  /** @minimum 0 */
  total_clients: number;
  total_hashrate: number;
}

/**
 * Aggregate information about all Sv2 clients
 */
export interface Sv2ClientsSummary {
  /** @minimum 0 */
  extended_channels: number;
  /** @minimum 0 */
  standard_channels: number;
  /** @minimum 0 */
  total_channels: number;
  /** @minimum 0 */
  total_clients: number;
  total_hashrate: number;
}

/**
 * Global statistics from `/api/v1/global` endpoint

Fields are `Option` to distinguish "not monitored" (`None`) from "monitored but empty" (`Some`
with zeros).

Typical configurations:
- **Pool/JDC**: `server` and `sv2_clients` are `Some`, `sv1_clients` is `None`
- **tProxy**: `server` and `sv1_clients` are `Some`, `sv2_clients` is `None`
 */
export interface GlobalInfo {
  server?: null | ServerSummary;
  sv1_clients?: null | Sv1ClientsSummary;
  sv2_clients?: null | Sv2ClientsSummary;
  /**
   * Uptime in seconds since the application started
   * @minimum 0
   */
  uptime_secs: number;
}

export interface HealthResponse {
  status: string;
  /** @minimum 0 */
  timestamp: number;
}

export type ServerExtendedChannelInfoSharesRejectedByReason = {[key: string]: number};

/**
 * Information about an extended channel opened with the server
 */
export interface ServerExtendedChannelInfo {
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  extranonce_prefix_hex: string;
  /** @minimum 0 */
  full_extranonce_size: number;
  /**
   * None when vardiff is disabled and hashrate cannot be reliably tracked
   * @nullable
   */
  nominal_hashrate?: number | null;
  /** @minimum 0 */
  rollable_extranonce_size: number;
  share_work_sum: number;
  /** @minimum 0 */
  shares_acknowledged: number;
  /** @minimum 0 */
  shares_rejected: number;
  shares_rejected_by_reason: ServerExtendedChannelInfoSharesRejectedByReason;
  /** @minimum 0 */
  shares_submitted: number;
  target_hex: string;
  user_identity: string;
  version_rolling: boolean;
}

export type ServerStandardChannelInfoSharesRejectedByReason = {[key: string]: number};

/**
 * Information about a standard channel opened with the server
 */
export interface ServerStandardChannelInfo {
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  extranonce_prefix_hex: string;
  /**
   * None when vardiff is disabled and hashrate cannot be reliably tracked
   * @nullable
   */
  nominal_hashrate?: number | null;
  share_work_sum: number;
  /** @minimum 0 */
  shares_acknowledged: number;
  /** @minimum 0 */
  shares_rejected: number;
  shares_rejected_by_reason: ServerStandardChannelInfoSharesRejectedByReason;
  /** @minimum 0 */
  shares_submitted: number;
  target_hex: string;
  user_identity: string;
}

export interface ServerChannelsResponse {
  extended_channels: ServerExtendedChannelInfo[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  standard_channels: ServerStandardChannelInfo[];
  /** @minimum 0 */
  total_extended: number;
  /** @minimum 0 */
  total_standard: number;
}

export interface ServerResponse {
  /** @minimum 0 */
  extended_channels_count: number;
  /** @minimum 0 */
  standard_channels_count: number;
  total_hashrate: number;
}

/**
 * Information about a standard channel
 */
export interface StandardChannelInfo {
  best_diff: number;
  /** @minimum 0 */
  blocks_found: number;
  /** @minimum 0 */
  channel_id: number;
  expected_shares_per_minute: number;
  extranonce_prefix_hex: string;
  /** @minimum 0 */
  last_batch_accepted: number;
  last_batch_work_sum: number;
  /** @minimum 0 */
  last_share_sequence_number: number;
  nominal_hashrate: number;
  requested_max_target_hex: string;
  /** @minimum 0 */
  share_batch_size: number;
  share_work_sum: number;
  /** @minimum 0 */
  shares_accepted: number;
  target_hex: string;
  user_identity: string;
}

/**
 * Information about a single SV1 client connection
 */
export interface Sv1ClientInfo {
  authorized_worker_name: string;
  /**
   * @minimum 0
   * @nullable
   */
  channel_id?: number | null;
  /** @minimum 0 */
  client_id: number;
  extranonce1_hex: string;
  /** @minimum 0 */
  extranonce2_len: number;
  /** @nullable */
  hashrate?: number | null;
  target_hex: string;
  user_identity: string;
  /** @nullable */
  version_rolling_mask?: string | null;
  /** @nullable */
  version_rolling_min_bit?: string | null;
}

export interface Sv1ClientsResponse {
  items: Sv1ClientInfo[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  /** @minimum 0 */
  total: number;
}

export interface Sv2ClientChannelsResponse {
  /** @minimum 0 */
  client_id: number;
  extended_channels: ExtendedChannelInfo[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  standard_channels: StandardChannelInfo[];
  /** @minimum 0 */
  total_extended: number;
  /** @minimum 0 */
  total_standard: number;
}

/**
 * Full information about a single Sv2 client including all channels
 */
export interface Sv2ClientInfo {
  /** @minimum 0 */
  client_id: number;
  extended_channels: ExtendedChannelInfo[];
  standard_channels: StandardChannelInfo[];
}

/**
 * Sv2 client metadata without channel arrays (for listings)
 */
export interface Sv2ClientMetadata {
  /** @minimum 0 */
  client_id: number;
  /** @minimum 0 */
  extended_channels_count: number;
  /** @minimum 0 */
  standard_channels_count: number;
  total_hashrate: number;
}

export interface Sv2ClientResponse {
  /** @minimum 0 */
  client_id: number;
  /** @minimum 0 */
  extended_channels_count: number;
  /** @minimum 0 */
  standard_channels_count: number;
  total_hashrate: number;
}

export interface Sv2ClientsResponse {
  items: Sv2ClientMetadata[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  /** @minimum 0 */
  total: number;
}